services:
  db:
    image: postgres:17.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pg-store:/var/lib/postgresql/data
    ports:
      - 5434:5432

volumes:
  pg-store:
